# Use the latest Nginx image
FROM nginx:latest

# Copy file into the container
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end

#Copy file into the container
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf