# Use the latest Ubuntu image
FROM ubuntu:latest

# Update the package list
RUN apt-get update

# Upgrade all currently installed packages
RUN apt-get upgrade -y

# The command for display Hello World!
CMD ["echo", "Hello, World!"]